# ORYX_ENABLE = yes
# TAP_DANCE_ENABLE = yes
# LAYER_LOCK_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
ORYX_ENABLE = yes
RGB_MATRIX_CUSTOM_KB = yes
TAP_DANCE_ENABLE = no
SPACE_CADET_ENABLE = no

# POST_CONFIG_H += keyboards/zsa/tsujp/config.h
